// 代码生成时间: 2025-08-15 17:17:13
 *              to create a REST API that can generate and return test data.
 * @author Your Name
 * @version 1.0
 */
package com.example;

import io.dropwizard.Application;
import io.dropwizard.configuration.Environment;
import io.dropwizard.setup.Bootstrap;
import io.dropwizard.setup.Environment;
import io.dropwizard.views.View;
import io.dropwizard.views.mustache.MustacheViewRenderer;
import io.dropwizard.views.mustache.MustacheViewRenderer;
import io.dropwizard.views.ViewBundle;
import io.dropwizard.views.View;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import java.util.Random;

@Path("/test-data")
public class TestDataResource {

    private final Random random = new Random();

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public String generateTestData() {
        // Generate test data
        String data = "Data generated by random number: " + random.nextInt();
        return data;
    }
}

public class TestDataGenerator extends Application<Configuration> {
    public static void main(String[] args) throws Exception {
        new TestDataGenerator().run(args);
    }

    @Override
    public void initialize(Bootstrap<Configuration> bootstrap) {
        // Initialize ViewRenderer for rendering Mustache templates
        bootstrap.addBundle(new ViewBundle<Configuration>() {
            @Override
            public void run(Configuration configuration, Environment environment) {
                environment.getViewRenderers().registerMustacheFactory();
            }
        });
    }

    @Override
    public void run(Configuration configuration, Environment environment) {
        // Register resources
        environment.jersey().register(new TestDataResource());
    }
}
